
var token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyTmFtZSI6ImFkbWluIiwidHlwZSI6ImFkbWluIiwiaWF0IjoxNDY0MDgxMTU4LCJleHAiOjE0NjQxNjc1NTh9.CDR7Bl5EQ6ZpBhfwqd5QgJP_MA2SxY_s_sM_iAuXu7A';

module.exports = token;
