var token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyTmFtZSI6ImFkbWluIiwidHlwZSI6ImFkbWluIiwiaWF0IjoxNDYzMTM2MjIyLCJleHAiOjE0NjMyMjI2MjJ9.xNq6_hChHxUCgiJZ6DLRMbIbm25naACFiladgTLHuIM';
module.exports = token;
